### ISSUE TITLE
Issue on running sse.py file

### ISSUE THREAD

**Issue by Talha705** [ChisomOkwor/AI_PersonTrainer#3]
i am using python 3.16 version
When i try to run sse.py file after installing modules then it says module 'mediapipe' has no attribute 'solutions' and it generating an error
Traceback (most recent call last):
  File "AI_PersonTrainer/sse.py", line 6, in <module>
    import ExercisesModule as trainer
  File "/AI_PersonTrainer/ExercisesModule.py", line 11, in <module>
    import face_detection as face_det
  File "AI_PersonTrainer/face_detection.py", line 5, in <module>
    mp_face_detection = mp.solutions.FaceDetection()
AttributeError: module 'mediapipe' has no attribute 'solutions'

**Comment by Talha705** [comment]
Can you see this issue as it is urgent
